#!/opt/csw/bin/perl
#
use warnings;
use strict;

use lib "/opt/rt3/lib";

use RT::Interface::CLI qw(CleanEnv loc);

#Clean out all the nasties from the environment
CleanEnv();

# let's talk to RT
use RT::Tickets;
use Data::Dumper;

# Load RT's config file
RT::LoadConfig();

# Connect to the database. Set up logging
RT::Init();

print loc('Hello!') . "\n";

my $tickets= new RT::Tickets($RT::SystemUser);
$tickets->OrderBy( FIELD => 'id', ORDER => 'ASC' );
$tickets->LimitStatus(VALUE => 'new');

# Print how many tickets we have
my $count = $tickets->Count;
print "\$tickets->Count is ".$tickets->Count."\n";


while (my $ticket = $tickets->Next) {
  print $ticket->id . "\n"; 
}
